### ISSUE TITLE
How to add content to sections?

### ISSUE THREAD

**Issue by chrieke** [victoryhb/streamlit-option-menu#1]
This looks fantastic! After playing around with it for a bit, could you please add an example how I add content to a section or trigger an event? I might be missing something, I imagined something like `selected.Home.write("abc")`  etc.

**Comment by victoryhb** [comment]
Hi @chrieke, separating the items into sections is a reasonable request and I just added a simple way to add a separator between option items:
```
selected = option_menu("Main Menu", ["Home", "---", 'Settings'],
        icons=['house', None, 'gear'], menu_icon="cast", default_index=1)
```
where setting an option to "---" will insert a section separator.

To "trigger an event" in Streamlit, you just select an option, which will be passed to the backend for you to act on. For example, you can decide what to do once the selected option changes:
```
if selected == "Home":
    # do something
else:
    # do something else
```
