### ISSUE TITLE
streamlit_book built on top of streamlit-option-menu

### ISSUE THREAD

**Issue by sebastiandres** [victoryhb/streamlit-option-menu#10]
Hi! 

  Not an issue or error. 

  I just wanted to let you know that the library is great and I'm using it complement the library streamlit-book I'm developing:
https://github.com/sebastiandres/streamlit_book
https://streamlit-book.readthedocs.io/en/latest/
(The library adds multipages with previous/next pagination on top of "chapters" and markdown rendering + activities)

Thanks for this awesome component! It makes my life waaaay easier and it's super profesional looking!

**Comment by victoryhb** [comment]
Hi @sebastiandres, thanks for the kind words! I am glad you find the component useful. I checked out your library and it looks awesome! Keep up the good work :)
