### ISSUE TITLE
In the sidebar, how can I adjust the margin? 

### ISSUE THREAD

**Issue by chiehpower** [victoryhb/streamlit-option-menu#11]
Hi @victoryhb ,

Thanks for this awesome component of your contribution!

I have one question how can I adjust the margin (or bandwidth) as you can see in the image below.

![2022-04-0737](https://user-images.githubusercontent.com/32332200/162109888-394fe7b3-1bd3-4818-ad95-8510d29442b1.png)

I applied the option_menu and streamlit default components at the same time. Because I do not want to display the container, I adjust the `background-color` of `container` of `option_menu` as same as sidebar color. Hence, each option of "nav-link" is a little bit narrower than streamlit default components. I am wondering is it possible to adjust the width of "nav-link" being as same width as the streamlit default components?
Besides, how can I change the icon color of "nav-link-selected"? Since if I add the "color" in the "nav-link-selected", it only changes the color of the word. 

Here is my code:
```
with st.sidebar:
    
    app_mode = option_menu(None, ["Home", "Models", "Inference", "Project"],
                        icons=['house', 'sliders', 'person-bounding-box', 'kanban'],
                        menu_icon="app-indicator", default_index=0,
                        styles={
        "container": {"padding": "5!important", "background-color": "#f0f2f6"},
        "icon": {"color": "orange", "font-size": "28px"}, 
        "nav-link": {"font-size": "16px", "text-align": "left", "margin":"0px", "--hover-color": "#eee"},
        "nav-link-selected": {"background-color": "#2C3845"},
    }
    )
```

One more question. I found the central position of the word which is a little bit lower than central point of the icon.
![2022-04-0749](https://user-images.githubusercontent.com/32332200/162110952-4af0dffa-0102-4ef3-adc1-a756a9343c44.png)

Is it possible to adjust as well?

Thank you in advance!

Best regards, 
Chieh

**Comment by victoryhb** [comment]
Hi @chiehpower,
> I have one question how can I adjust the margin (or bandwidth) as you can see in the image below.

Not sure if I understand what you mean, maybe just set the "padding" of the container to "0!important"?

> Besides, how can I change the icon color of "nav-link-selected"?

Currently not supported; might add that in the future.

> I found the central position of the word which is a little bit lower than central point of the icon.

This is not a problem related to the component itself, but a CSS problem:
You may try the following on "nav-link":
```
    display: flex;
    align-items: center;
```

**Comment by chiehpower** [comment]
hi @victoryhb 

Thanks for your reply and explanation!!

1. "0!important" does work!!

2. Got it! Really looking forward to it!

3. After I added your suggestion into "nav-link` like this `"nav-link": {"font-size": "16px", "text-align": "left", "margin":"0px", "--hover-color": "#eee", "display": "flex", "align-items": "center"}` , it does work!!
![image](https://user-images.githubusercontent.com/32332200/162648050-08d667a5-4073-4f80-b5c9-f8a5f3585766.png)

Thank you so much!!

BR,
Chieh
