### ISSUE TITLE
Nested options

### ISSUE THREAD

**Issue by backtr4ck** [victoryhb/streamlit-option-menu#15]
It would be great if you could add nested options, returning the selection as a list and/or comma-separated string.

**Comment by hikmatilloahatov** [comment]
> It would be great if you could add nested options, returning the selection as a list and/or comma-separated string.

right

**Comment by sridharrajaram** [comment]
@hikmatilloahatov can you help in creating this nested selection features. example once we selecting or hover the menu, submenu kinda stuff. If we hover over the profile icon, menu like profile setting, change password, logout..

**Comment by CHerSun** [comment]
I'd love hierarchical menu too.

Maybe in a form of just dict of menu name to result (keeping other things the same). If result is another dict - add sublevel to menu. Returning either a tuple of name+result or just result.

**Comment by CHerSun** [comment]
@backtr4ck could you comment on issue closing pls? Was this implemented, or did you find some other solution?
