### ISSUE TITLE
Integration with the new streamlit multi page feature

### ISSUE THREAD

**Issue by franasal** [victoryhb/streamlit-option-menu#19]
I have tried to use this awesome extension with the latest streamlit update (streamlit-1.11.0) but so far have been unsuccessful. when I use the `with st.sidebar` block as It was previously working:

```python

with st.sidebar:
 selection = option_menu("", "Substanzen"),
 icons=['file-earmark-text'], menu_icon="cast", default_index=0,
 styles={
     "nav-link": {"font-size": "16px", "text-align": "left", "margin":"0px"},
     "nav-link-selected": {"background-color": "ffffff"},
 }) 
```

I get the syntax error 

```
   icons=['file-earmark-text'], menu_icon="cast", default_index=0,
   ^
SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='?
```
I guess the option menu is not compatible with the multi page feature yet?

**Comment by Socvest** [comment]
Try [this](https://discuss.streamlit.io/t/trick-simple-multpage/26121) implementation

**Comment by franasal** [comment]
Thanks @Socvest , that looks clean! Although my question is also in line with what `miro` [commented]:(https://discuss.streamlit.io/t/trick-simple-multpage/26121/5)

> Is there a way that we can actually leverage the new Streamlit 1.10 Multi-Page functionality where each page has a unique URL?

**Comment by Socvest** [comment]
> Thanks @Socvest , that looks clean! Although my question is also in line with what `miro` [commented](https://discuss.streamlit.io/t/trick-simple-multpage/26121/5):
> 
> > Is there a way that we can actually leverage the new Streamlit 1.10 Multi-Page functionality where each page has a unique URL?

Ahh, I see. Not sure about that unfortunately.

**Comment by CHerSun** [comment]
@franasal I'm pretty sure this is no longer actual, but decided to answer, seeing that issue is not closed yet. 

You have a syntax error - closing bracket `)` on your first line after `with`, that's the error, not with the options menu. Options menu works perfectly fine with multipage apps.
