### ISSUE TITLE
Direct link to pre-selected items

### ISSUE THREAD

**Issue by giswqs** [victoryhb/streamlit-option-menu#2]
Thank you for develop this nice streamlit component. Would it be possible to add support for getting direct link to pre-selected menu? 

Relevant issues:
https://discuss.streamlit.io/t/direct-link-to-pre-selected-items/4817
https://github.com/streamlit/streamlit/pull/1169

**Comment by victoryhb** [comment]
Hi @giswqs, if I understood what you mean, letting users pre-select an option through a URL parameter is feasible in Streamlit, but in my opinion should be implemented at the *app* level, not the component level. 
I would imagine doing something like the following:

Given a URL like http://localhost?selected_index=1
```
params = st.experimental_get_query_params()
selected = option_menu("Menu Title", ["option1", "option2"], default_index=int(params['selected_index'][0]))
if selected == "option1": 
    # show the page for option1
```

**Comment by victoryhb** [comment]
Hi @giswqs, if I understood what you mean, letting users pre-select an option through a URL parameter is feasible in Streamlit, but in my opinion should be implemented at the *app* level, not the component level. 
I would imagine doing something like the following:

Given a URL like http://localhost?selected_index=1
```
params = st.experimental_get_query_params()
selected = option_menu("Menu Title", ["option1", "option2"], default_index=int(params['selected_index'][0]))
if selected == "option1": 
    # show the page for option1
```

**Comment by giswqs** [comment]
Thanks for the suggestion. I was able to implement it. 
https://share.streamlit.io/giswqs/streamlit-template
