### ISSUE TITLE
how to use streamlit options menu on multiple pages

### ISSUE THREAD

**Issue by wraza2k9** [victoryhb/streamlit-option-menu#22]
I want to know how to use the components on multiple pages of the same app?
Thanks.

**Comment by RAravindDS** [comment]
@wraza2k9 Please check the `st.tabs`, We are using this for multiple tabs. Link to [**Documentatin**](https://docs.streamlit.io/library/api-reference/layout/st.tabs) you can refer this. If you want multiple tabs with multiple pages you can refer [**this**](https://www.youtube.com/watch?v=hEPoto5xp3k). Hope it helps.

**Comment by wraza2k9** [comment]
Thanks
