### ISSUE TITLE
Some icons does not show

### ISSUE THREAD

**Issue by suaide** [victoryhb/streamlit-option-menu#25]
I am trying to use some icons from bootstrap library, such as 'database' and they do not show on the menu. It happens for some other icons. How do I fix it?

**Comment by FrocketGaming** [comment]
I too am having the same problem. None of the filetype- icons work, such as filetype-json

**Comment by littlepanda0716** [comment]
Perhaps it’s problem about the bootstrap icon version, icons like database were updated in v1.10.0

**Comment by victoryhb** [comment]
Bootstrap icons have been updated to the latest version.
