### ISSUE TITLE
open external link

### ISSUE THREAD

**Issue by isezen** [victoryhb/streamlit-option-menu#28]
Is it possible to open an external link when click the menu item?

**Comment by fgdvir** [comment]
You can do it with streamlit and python code, its not a part of the menu. you can look for example on this [discuttion](https://discuss.streamlit.io/t/how-to-redirect-streamlit-to-a-external-url-without-open-a-new-tab/21929) and see how you can do it in streamlit. Then just add a condition in the code the if a specific option is chosen, you open the url
