### ISSUE TITLE
menu bar not filling full width

### ISSUE THREAD

**Issue by lcalmbach** [victoryhb/streamlit-option-menu#3]
hi!
first: thank you so much for this compenent, it is truly awesome.
I am working on an application where the horizotal menu-option would come in handy.  I have 7 menu items and unfortunately icons and labels are starting to show in separate lines, even if there is enough space. I would prefer them to stay on a single line and also to be left adjusted. In addition the top margin could be set to zero, so there is less blank space. I am aware that these may be limitations of streamlit, but maybe there is a workaround? This is a feature request rather than a issue, if you prefer I can post this elsewhere, e.g. on the streamlit discussion forum. Just let me know. Thanks again for this wonderful component. 

![menu_bar_fontus](https://user-images.githubusercontent.com/20972598/151690971-35821796-4345-4978-bc90-20bf082f69a8.png)

**Comment by victoryhb** [comment]
Hi @lcalmbach thanks for the note. That definitely seems fixable (may add some options to allow CSS style definition). I will get back to you when it's done (I am currently on holiday so it may take longer than usual)

**Comment by lcalmbach** [comment]
awesome, there is absolutely no rush, as everything is working, it would be just nicer on a single line. thanks again for looking into this

**Comment by qianchen94** [comment]
I met the same problem, when i switch the icon to another, the width of the bar is changing and can't fill the width

**Comment by victoryhb** [comment]
Hi @lcalmbach @qianchen94 the problem has been fixed in the latest release, please upgrade :)

**Comment by lcalmbach** [comment]
fantastic, in version 0.3.2 the menu bar adjusts perfectly and the menu items apprera on 2 lines only when required. thanks so much for the fast fix.
