### ISSUE TITLE
How do you move the entire div up by a few pixels?

### ISSUE THREAD

**Issue by mansidak** [victoryhb/streamlit-option-menu#31]
I'm trying to move the entire block up by 20 px but for some reason only the icons move up leading to something like this:

![Screenshot 2023-03-28 at 9 26 58 PM](https://user-images.githubusercontent.com/51833970/228426702-7f4fd856-219c-4562-bd25-d63b53cc1240.png)

This is my code:

` 
   
                                selected2 = option_menu(None, ["Home", "Search", "Build", 'Dashboard'],
                                icons=['house', 'search', "file-earmark-font", 'stack'],
                                menu_icon="cast", default_index=0, orientation="horizontal",
                                styles={
                                    "container": {"margin-top": "-20px!important", "background-color": "#0f0f0f"},
                                    "nav-link": {"font-size": "15px", "text-align": "center", "margin": "0px",
                                                 "--hover-color": "#0f0f0f", "color": "white",
                                                 "background-color": "#0f0f0f"},
                                    "nav-link-selected": {"font-weight": "bold", "background-color": "#0f0f0f",
                                                          "color": "#F63366"},

                                })
`

**Comment by fgdvir** [comment]
I don't think this would work since the component live in an Iframe and by doing what you did, you are basically telling it to go out of the Iframe.
