### ISSUE TITLE
Icons break with a simple reproducible example

### ISSUE THREAD

**Issue by israelg99** [victoryhb/streamlit-option-menu#35]
The issue is the max amount of icons on the menu is set depending on how many options the menu had on its first render, if options are added dynamically later they would be missing icons.

[GIF of the unexpected behavior](https://i.gyazo.com/c771488f08f9293648f7fefee2ee5bfb.mp4)

```python
pipes: dict[str, list[str]] = {}
pipes["pipe1"] = ["node1"]
pipes["pipe2"] = ["node1", "node2"]
pipes["pipe3"] = ["node1", "node2", "node3"]

with st.sidebar:
    st.header("Pipes")
    pipe = option_menu(
        None,
        list(pipes.keys()),
        icons=["bezier2" for _ in pipes.keys()],
        default_index=0,
        key="pipe",
    )

    st.header("Nodes")
    selected_node = option_menu(
        None,
        pipes[pipe],
        icons=["caret-right" for _ in pipes[pipe]],
        default_index=0,
        key="node",
    )
```

If `default_index=1` then it'll show icons successfully for the first 2 options, since on first render the `Nodes` menu would have 2 icons, but the last icon on the third option will be missing since it requires 3 icons - that's more than the original render.

**Comment by fgdvir** [comment]
Thanks.
It is fixed and I opened a [PR](https://github.com/victoryhb/streamlit-option-menu/pull/39).
I hope it will be approved and merged soon :)
