### ISSUE TITLE
`on_change` callback option

### ISSUE THREAD

**Issue by ujaved** [victoryhb/streamlit-option-menu#36]
Hi,

Great widget so far! I was wondering if there's support for an `on_change` callback, just like [selectbox](https://docs.streamlit.io/library/api-reference/widgets/st.selectbox)

**Comment by fgdvir** [comment]
Unfortunately, streamlit doesn't support callbacks for custom components.
You are welcome to vote for [issue 3977](https://github.com/streamlit/streamlit/issues/3977) and hopefully one day they will support it

**Comment by fgdvir** [comment]
@ujaved - After some more research, I found a workaround and opened a PR. follow for a working version soon.

**Comment by fgdvir** [comment]
Available in latest version. Closing
