### ISSUE TITLE
Hierarchical menu (nested)

### ISSUE THREAD

**Issue by CHerSun** [victoryhb/streamlit-option-menu#40]
Is it possible to add support for hierarchical menu? There are no such components for streamlit.

There was an issue opened for this #15, but original poster has closed that with no further info.

**Comment by fgdvir** [comment]
I did a workaround of just adding another option menu if a specific option is selected . not the prettiest but not so bad either

**Comment by CHerSun** [comment]
@fgdvir yep, doing the same thing, looks ugly really

**Comment by CHerSun** [comment]
> @CHerSun ,you can check this https://github.com/nicedouble/StreamlitAntdComponents.

@nicedouble interesting, I've missed that one, thank you, will check

**Comment by CHerSun** [comment]
@nicedouble I've checked the demo, looks awesome really! Both buttons, tabs, menu and tree. I'd really love to include this in my project, but problem is it's a company internal project and needs a clear license statement to include a new component. Could you please please decide on license and update the repo?
