### ISSUE TITLE
button option

### ISSUE THREAD

**Issue by iuiu34** [victoryhb/streamlit-option-menu#41]
Hi,
this option menu is very cool and pretty.

Would be possible to have it as a button?
So that you pass to `options` a single element. And click activates it/returns True, click deactivates it/returns False.

This may enter in conflict with `st.button`. But same applies now with option_menu & st.select_box.

thanks

example,
`option_menu (None, 'Upload')`
click -> 
![image](https://github.com/victoryhb/streamlit-option-menu/assets/30587996/91024007-5252-4b64-ba46-2f59356f6127)
click -> 
![image](https://github.com/victoryhb/streamlit-option-menu/assets/30587996/662f0af9-fbea-4de4-87d6-add6223e2ed8)

**Comment by iuiu34** [comment]
hi,
i achieved the button feature with the code below.
But i don't know JS, only python.
So code feels more monkey patching, than a proper new feature
And button changes color on click as desired, but doesn't feel reactive in the "pretty" sense

If we could have this functionality natively in the lib with JS i think would be very cool,
thanks

```py
def option_button_callback(key):
    print(key)
    key = key.split('_')[:-1]
    key = '_'.join(key)
    print(key)
    st.session_state[key] = not st.session_state[key]
    print(st.session_state[key])


def option_button(label, icon, background_color_on='blue', background_color_off='white',
                  color_on='black', color_off='white',
                  key=None):
    if key is None:
        key = label.lower().replace(' ', '_')
        key = f"{key}_option_button"

    if key not in st.session_state.keys():
        st.session_state[key] = False
    # st.sidebar.button(label, icon=icon, use_container_width=True)
    background_color = background_color_off if st.session_state[key] else background_color_on
    color = color_off if st.session_state[key] else color_on

    key_color = f"{key}_{background_color}"
    option_menu(
        None, [label],
        icons=[icon],
        styles={
            "container": {"padding": "0!important",
                          "background-color": "transparent"},
            "nav-link-selected": {"background-color": background_color,
                                  "color": color,
                                  "font-weight": "normal",

    }},
        on_change=option_button_callback,
        key=key_color,
        orientation="horizontal")

    return st.session_state[key]
   ```

**Comment by fgdvir** [comment]
I'm not sure what you are trying to get out of it. Why not use st.button? what will we gain by adding this functionality?

**Comment by iuiu34** [comment]
Prettier display,  react customizable colors, and the "bootstrap-icons".

Definetly overlaps with st.button functionality. 
But you could argue the same with option-menu & st.tabs, no?

**Comment by fgdvir** [comment]
You are right, but it meant to give a prettier tabs, not buttons.
