### ISSUE TITLE
format menu itens

### ISSUE THREAD

**Issue by suaide** [victoryhb/streamlit-option-menu#5]
This is a great addition to streamlit.

Is there a way to format the text in the menu? I mean, I realized that a clicked item shows in bold font. I want to change it to regular font. Is it possible?

**Comment by victoryhb** [comment]
Hi @suaide, functions to change CSS properties will be made available in an upcoming version. Please stay tuned :)

**Comment by victoryhb** [comment]
Thanks for reporting. It was a strange bug which just got fixed :)

**Comment by suaide** [comment]
thanks. It is a great component. Congratulations
