### ISSUE TITLE
Default as hidden

### ISSUE THREAD

**Issue by StarsExpress** [victoryhb/streamlit-option-menu#57]
Is it possible to set option_menu's default as hidden?
Such that it is hidden unless users click on it.

**Comment by StarsExpress** [comment]
![image](https://github.com/victoryhb/streamlit-option-menu/assets/105488074/8c661cce-8074-4636-9179-17946dedc5de)

As you see, this is the option menu of my app.
Every time I refresh entire page, this option menu jumps out.
I wonder if set hidden as default is available so that after refreshing this menu doesn't jump out, unless clicked by users.

Thank you so much~

**Comment by fgdvir** [comment]
Sorry, I still don't understand.
What do you mean by "Jump out"? 
By default, when you ask for a component on streamlit, it draws it, this applies to every streamlit component. I'm not really sure what kind of behavior are you looking for. 

Please try to explain again, or even give an example with images of what you would expect to happen (how it will look when page first initialize, what you are expecting the user to click, and how it will look after they will click it)

**Comment by fgdvir** [comment]
By "hidden" Do you mean collapsed? meaning you would like that initially only the title will show and when clicking on it it will expand ?

**Comment by StarsExpress** [comment]
> By "hidden" Do you mean collapsed? meaning you would like that initially only the title will show and when clicking on it it will expand ?

Yes, this is what I mean~
Make it collapsed as default~

**Comment by fgdvir** [comment]
I'm not sure if this is something that one would expect from a menu.
If enough people will like your request, maybe I can implement it

**Comment by fgdvir** [comment]
@StarsExpress 
I'm closing this issue since it might be confusing and not enough people would vote for this feature.
If you feel like this would be a feature other would need, please reopen with your image as example and explain that you want an expander like behavior for the menu

**Comment by fgdvir** [comment]
@StarsExpress
I'm closing this issue since it might be confusing and not enough people would vote for this feature.
If you feel like this would be a feature other would need, please reopen with your image as example and explain that you want an expander like behavior for the menu
