### ISSUE TITLE
vertical "---" separator with horizontal menu

### ISSUE THREAD

**Issue by chrieke** [victoryhb/streamlit-option-menu#6]
Love this addon! When using the separator "---" with a horizontal menu config, the separator should probably be vertical instead of horizontal.
Probably requires some condition with `is_Horizontal` in this [line](https://github.com/victoryhb/streamlit-option-menu/blob/662b05f40f0f44bc075254d778262ab0d7246df8/streamlit_option_menu/frontend/src/MyComponent.vue#L13). Tried my hand at it but still having some issues with the vue devserver setup, so opening this issue for now.

**Comment by victoryhb** [comment]
Hi @chrieke, thanks for reporting. Will look into this when I am back to work (currently on holiday).

**Comment by victoryhb** [comment]
Hi @chrieke, I changed the style of the hr somewhat, hopefully it can meet your needs.

**Comment by chrieke** [comment]
Awesome!
