### ISSUE TITLE
Two small details

### ISSUE THREAD

**Issue by dawaylee** [victoryhb/streamlit-option-menu#7]
Hi, I am currently facing two problems:

1. When I put the menu in the left column, there are many menu items, and then slide the mouse to the bottom, click a menu at this time, and then the menu bar will automatically slide to the top, and cannot stay in the currently selected menu. area, making it impossible to know the name of the currently clicked menu;
2. When the mouse slides over the menu, it is better to have a hint of a lighter color hot zone, which is more beautiful and practical.

Thank you so much for developing this module!

**Comment by victoryhb** [comment]
Hi @dawaylee, thank you for the note.
1. the first problem is inherently Streamlit's behavior and may not be easily fixable.
2. the second one can be solved with the latest version, please upgrade and read the docs :).
