### ISSUE TITLE
selected option vs just clicked an option

### ISSUE THREAD

**Issue by suaide** [victoryhb/streamlit-option-menu#9]
Is there a way to differentiate between an option that is selected from an option that was just clicked by the user? I mean, suppose I clicked a menu item in the past and streamlit just get that menu option every time it runs through the code. I wish to differentiate this from a menu item that was just clicked by the user. Is it possible?

**Comment by victoryhb** [comment]
I think you might just store the menu's value in the session state and check for changes every time?

**Comment by victoryhb** [comment]
If that's what you need, then a set of checkboxes might suit your needs better :). For more advanced solutions, you may want to ask the developers on the forum.
